name: deploy-container

on:
  push:
    branches: 
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directoriey: packages/container
  
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secreta.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ASSESS_KEY_ID: ${{ secreat.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secreta.AWS_SECRET_ACCESS_KEY }}
